version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  keycloak:
    image: jboss/keycloak:16.1.0
    container_name: keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    healthcheck:
      test: "curl -f http://localhost:8080/auth || exit 1"

  ticketing-app-container:
      image: ticketing-app-container
      container_name: ticketing-app-container
      ports:
        - "8085:8085"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ticketing?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: "root"
        SPRING_DATASOURCE_PASSWORD: "root"
      build:
        context: "./"
        dockerfile: "Dockerfile"
      depends_on:
        - mysql
        - keycloak